### ISSUE TITLE
Tried to install via shell command

### ISSUE THREAD

**Issue by wwendorf** [geneb/OctoPrint-Delta-Calibration#1]
This is the error I received.

I tried both:
pip install https://github.com/geneb/OctoPrint-Delta-Calibration/archive/master.zip
and
sudo pip install https://github.com/geneb/OctoPrint-Delta-Calibration/archive/master.zip

Command python setup.py egg_info failed with error code 255 in /tmp/pip-n1oL7s-build
Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by geneb** [comment]
So...where's the log?
If you're using OctoPi, try the version of pip that's in /home/pi/oprint/bin/.

**Comment by wwendorf** [comment]
Sorry, this was just running the command on the command line after a fresh
install of OctoPi.

I'll will try again and send you the few lines of messages that were on it.

Wade

**Comment by wwendorf** [comment]
sudo pip install https://github.com/geneb/OctoPrint-Delta-Calibrat
ion/archive/master.zip
Downloading/unpacking
https://github.com/geneb/OctoPrint-Delta-Calibration/archi
ve/master.zip
  Downloading master.zip (unknown size): 17kB downloaded
  Running setup.py (path:/tmp/pip-b8t4Lw-build/setup.py) egg_info for
package fr                        om
https://github.com/geneb/OctoPrint-Delta-Calibration/archive/master.zip
    Could not import OctoPrint's setuptools, are you sure you are running
that u                        nder the same python installation that
OctoPrint is installed under?
    Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running
that u                        nder the same python installation that
OctoPrint is installed under?

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 255 in
/tmp/pip-b8t4Lw-b                        uild
Storing debug log for failure in /root/.pip/pip.log





pi@octopi:~ $ cat  /root/.pip/pip.log
Downloading/unpacking
https://github.com/geneb/OctoPrint-Delta-Calibration/archive/master.zip
  Downloading from URL
https://github.com/geneb/OctoPrint-Delta-Calibration/archive/master.zip
  Running setup.py (path:/tmp/pip-b8t4Lw-build/setup.py) egg_info for
package from
https://github.com/geneb/OctoPrint-Delta-Calibration/archive/master.zip
    Could not import OctoPrint's setuptools, are you sure you are running
that under the same python installation that OctoPrint is installed under?
    Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running
that under the same python installation that OctoPrint is installed under?

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 255 in
/tmp/pip-b8t4Lw-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in
main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line
290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle,
bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in
prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in
run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in
call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code
255 in /tmp/pip-b8t4Lw-build

**Comment by geneb** [comment]
"If you're using OctoPi, try the version of pip that's in /home/pi/oprint/bin/."

**Comment by wwendorf** [comment]
That worked!  Thanks!
