### ISSUE TITLE
getting Your machine is not a SeeMeCNC 3D printer!

### ISSUE THREAD

**Issue by gurusonwheels** [geneb/OctoPrint-Delta-Calibration#3]
i updated my rostock max2 with upgraded he280 today to the latest firmware 
done g29 and calibrated 

however when i run your script i see 

Connection Status: connected
Your machine is not a SeeMeCNC 3D printer!

seems the script does not like the latest firmware . 

> #define REPETIER_VERSION "0.92.2"
> #define FIRMWARE_DATE "20170414" // in date format yyyymmdd

**Comment by gurusonwheels** [comment]
if i power off and on a couple time it sees it as a rostock . 
but clicking load eeprom then calibrate does nothing at all .

was working with older 2016 firmware

**Comment by T3CHKOMMIE** [comment]
I have the same problem Max v2 with HE280 and ball-cup arm upgrades. Some times its ok and runs, most of the time it says i dont have a SeeMeCNC printer, running the same 0.92.2 firmware.

**Comment by geneb** [comment]
This one has been pretty hard to pin down.  I'll dig into it a bit more and see if I can get it to behave.

**Comment by T3CHKOMMIE** [comment]
Thanks. I tired changing the js on my box to force checks to true, but the
calibration script would move only a little and hang. My suspicon is the
script is struggling to get eeprom info. Maybe timing? I've got octopi on a
RM 2 with v3 upgrades. Same v2 8bit board tho.

Let me know of you need help. My issue happens all the time now.

Jules

**Comment by BuildAndDie** [comment]
Have a Rostock Max v3 and having this issue as well. Any update, or workaround?

**Comment by geneb** [comment]
Can you give me some of the console data that the plugin sends?  If you're using Chrome, open Octoprint and then hit F12 to open the script debugging window.  Click on the "Console" tab and then open up the calibration plugin. In the console, you should see something like this:
Firmware: Recv: FIRMWARE_NAME:Repetier_0.92.2 
FIRMWARE_DATE:20170414 MACHINE_TYPE:Rostock MAX v3 Dual
Printer Rostock Max v3

Please reply with what your printer sends when you open the plugin.

Thanks!

g.

**Comment by BuildAndDie** [comment]
hmmm.... not sure, console isn't showing anything like that at all, either when I first load octoprint nor when I go to click on the plugin. I had to make it view "Verbose" to see more stuff, and there's some violations, but I'm not sure if that's related to octoprint or your thing.

When I click "Load EEprom" it does stuff, I can see it happening in the console showing all the values of the eeprom.

When I type "M115" in the terminal for the printer I get back:

FIRMWARE_NAME:Repetier_0.92.2 FIRMWARE_DATE:20171204 MACHINE_TYPE:Rostock MAX v3

**Comment by BuildAndDie** [comment]
![octoprint 01](https://user-images.githubusercontent.com/23116144/35785468-344a4896-09e6-11e8-8463-f54dcae8b98a.jpg)
![octoprint 02](https://user-images.githubusercontent.com/23116144/35785472-3661f390-09e6-11e8-9ba3-57f084f2b126.jpg)

**Comment by BuildAndDie** [comment]
alright, so weird thing, it suddenly, for first time, said it is a seemecnc printer... wonder it it is b/c I did the "M115" in the terminal of octoprint?

**Comment by BuildAndDie** [comment]
To follow up, the next day, same thing again. Says not a SeeMeCNC 3D printer. Doesn't seem to ever ask for what the printer is though, nothing in the "F12" has any message about the name of the printer in it. It does say "Connected" under the connection status.

M115 to the terminal didn't do anything this time.

-----
Rereshed Octoprint several times, and finally on one refresh it worked as reading it.

**Comment by BuildAndDie** [comment]
Wow, ok, so after a lot of messing around, it seems the problem was that one of my accelorometer wires was just a tad lose on the hotend area. I've got that fixed, and things seem to be working fine now, it recognized the printer on the first time, so that was probably the problem?

**Comment by geneb** [comment]
So as of right now, you're able to use the calibration program without any problems?  I'll try to contact gurusonwheels to see if he's still having an issue.  The plugin does issue an M115 on startup.
I'm going to be posting a new update that changes the probing to 16 points from 10.

**Comment by BuildAndDie** [comment]
Just tested this morning, and no, I'm getting it saying it is not a SeeMeCNC machine again. Seems like it is just random? Looking at the terminal in Octoprint, it seems 2 different M115 commands are being sent, not sure if either one is from the plugin though. When I go to the plugin it doesn't seem to send a command to ask.

It did work just great yesterday to do the calibration though when it actually read it as a seemecnc machine. I tested to make sure there was no problems with the accelerometer like before, and I'm not having issues with teh G29 command at all, so I don't think it is that.

------

EDIT: Like, for example, just restarted Octoprint a few times and for some reason now it says it is a seemecnc machine, reading it as the rostock max v3.................

------

EDIT2: To be more clear, it wasn't so much that I restarted Octoprint, as I closed the tab it was in, and relaunched the the page. I've also gone through Octoprint and doing a reboot on that and it didn't seem to do anything in the past.

So I tested by restarting the machine itself, and on first load-up, once again, it says not SeeMeCNC machine. I'm not sure if it's a load time thing, maybe the machine needs to be on for so long, or Octoprint needs to be on for so long? After several reloads of the octoprint webpage it is now reading it correctly again.

**Comment by geneb** [comment]
I just updated the code for the 16 point bed probe - give it a shot. :)  Do an M502 to reload defaults then a G29, then run the calibration.
I don't know what to tell you regarding the detection - I had an issue similar to yours the other day, but I wasn't getting any traffic in the debug window at all.  Restarting OctoPrint and then reloading the browser cleared the issue.

**Comment by BuildAndDie** [comment]
Had to do the multiple reload thing to get it to register, so I think it is just a browser/connection thing on that end.

Ran it, and it did the 16 point calibration. I did notice it didn't do a center point (dead center of the build plate), but I'm guessing that is as intended b/c of the more points.

**Comment by geneb** [comment]
I'm glad it's working for you finally - even though it's a hassle. :(  At some point I may build a stand-alone version of the tool that won't require Octoprint, but right now I don't have the spare time.

g.
